import type { ExplorationOptions } from '@raceproof/explorer';
import type { ExampleId, ExampleVariant } from '@raceproof/examples';

export interface RegressionTestInput {
  readonly exampleId: ExampleId;
  readonly variant: ExampleVariant;
  readonly transitionIds: readonly string[];
  readonly invariantId: string;
  readonly invariantTitle: string;
  readonly options?: Pick<ExplorationOptions, 'algorithm' | 'maxDepth' | 'maxStates' | 'timeoutMs' | 'randomSeed'>;
}

const SYSTEM_IMPORTS: Record<ExampleId, Record<ExampleVariant, string>> = {
  payment: { buggy: 'paymentBuggy', fixed: 'paymentFixed' },
  inventory: { buggy: 'inventoryBuggy', fixed: 'inventoryFixed' },
  chat: { buggy: 'chatBuggy', fixed: 'chatFixed' },
};

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

/**
 * Build portable source rather than evaluating it. The selected bundled system
 * is imported by a stable package name, so the source never contains a local
 * path from the user's machine.
 */
export function generateVitestRegressionTest(input: RegressionTestInput): string {
  const importedSystem = SYSTEM_IMPORTS[input.exampleId][input.variant];
  const options = input.options;
  const comments = [
    '// Generated by RaceProof. Keep this regression beside the implementation it protects.',
    `// Variant: ${input.variant}; invariant: ${input.invariantTitle}`,
    ...(options?.algorithm === undefined ? [] : [`// Algorithm: ${options.algorithm}`]),
    ...(options?.randomSeed === undefined ? [] : [`// Random seed: ${options.randomSeed}`]),
    ...(options?.maxDepth === undefined ? [] : [`// Bounds: depth ${options.maxDepth}, states ${options.maxStates ?? 'default'}, timeout ${options.timeoutMs ?? 'default'}ms`]),
  ];

  return `${comments.join('\n')}
import { describe, expect, it } from 'vitest';
import { ${importedSystem} as system } from '@raceproof/examples';
import { replayTrace } from '@raceproof/explorer';

describe(${literal(`RaceProof regression: ${input.exampleId}`)}, () => {
  it(${literal(input.invariantTitle)}, () => {
    const trace = ${literal([...input.transitionIds])};
    const replay = replayTrace(system, trace);

    // Every retained event must still be valid in this exact order.
    expect(replay.ok, replay.failure?.message).toBe(true);
    expect(replay.steps).toHaveLength(trace.length);

    const invariant = replay.finalInvariants.find((candidate) => candidate.id === ${literal(input.invariantId)});
    expect(invariant, 'The selected invariant must exist.').toBeDefined();
    // This assertion fails for a buggy model and passes once the same scenario is fixed.
    expect(invariant?.passed).toBe(true);
  });
});
`;
}

export function regressionDownloadFilename(input: Pick<RegressionTestInput, 'exampleId' | 'variant'>): string {
  const safeExample = input.exampleId.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const safeVariant = input.variant.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  return `raceproof-${safeExample}-${safeVariant}.test.ts`;
}
